### ISSUE TITLE
Error in xpore-dataprep step

### ISSUE THREAD

**Issue by madnessfish** [GoekeLab/xpore#24]
I have encountered some problems while running the xpore-dataprep step. I have mapped the raw DRS reads to human reference transcriptome with minimap2.  I wondered if it is related to the read_index in the summary file. Thank you so much!

eventalign.txt
![eventalign](https://user-images.githubusercontent.com/29503972/89299915-ffe8ab00-d699-11ea-8609-d3cb018c0353.PNG)

summary.txt
![summary](https://user-images.githubusercontent.com/29503972/89299940-070fb900-d69a-11ea-9e82-a4a752ef4185.PNG)

command
`xpore-dataprep --eventalign eventalign.txt --summary summary.txt --out_dir dataprep`

It raise the error below.
Process Consumer-1:
Traceback (most recent call last):
  File "/exeh_2/sin/bin/miniconda3/envs/xpore/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/exeh_2/sin/bin/miniconda3/envs/xpore/lib/python3.8/site-packages/xpore/scripts/helper.py", line 77, in run
    result = self.task_function(*next_task_args,self.locks)
  File "/exeh_2/sin/bin/miniconda3/envs/xpore/lib/python3.8/site-packages/xpore/scripts/dataprep.py", line 78, in combine
    df2write = df_events_per_read.loc[[tx_id,read_id],:].reset_index()
  File "/exeh_2/sin/bin/miniconda3/envs/xpore/lib/python3.8/site-packages/pandas/core/indexing.py", line 873, in __getitem__
    return self._getitem_tuple(key)
  File "/exeh_2/sin/bin/miniconda3/envs/xpore/lib/python3.8/site-packages/pandas/core/indexing.py", line 1044, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "/exeh_2/sin/bin/miniconda3/envs/xpore/lib/python3.8/site-packages/pandas/core/indexing.py", line 766, in _getitem_lowerdim
    return self._getitem_nested_tuple(tup)
  File "/exeh_2/sin/bin/miniconda3/envs/xpore/lib/python3.8/site-packages/pandas/core/indexing.py", line 847, in _getitem_nested_tuple
    obj = getattr(obj, self.name)._getitem_axis(key, axis=axis)
  File "/exeh_2/sin/bin/miniconda3/envs/xpore/lib/python3.8/site-packages/pandas/core/indexing.py", line 1099, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
  File "/exeh_2/sin/bin/miniconda3/envs/xpore/lib/python3.8/site-packages/pandas/core/indexing.py", line 1037, in _getitem_iterable
    keyarr, indexer = self._get_listlike_indexer(key, axis, raise_missing=False)
  File "/exeh_2/sin/bin/miniconda3/envs/xpore/lib/python3.8/site-packages/pandas/core/indexing.py", line 1240, in _get_listlike_indexer
    indexer, keyarr = ax._convert_listlike_indexer(key)
  File "/exeh_2/sin/bin/miniconda3/envs/xpore/lib/python3.8/site-packages/pandas/core/indexes/multi.py", line 2397, in _convert_listlike_indexer
    raise KeyError(f"{keyarr[mask]} not in index")
KeyError: "['29dfb566-2dbe-4b8f-8c3e-ba2f6d1403e9'] not in index"

**Comment by ploy-np** [comment]
Hi @madnessfish, 
May I ask what version of xpore do you use? We encourage you to use xpore v0.5.2.

**Comment by pabloacera** [comment]
Hi! I am running the demo code with the 0.5.2 version and still get a similar error
```
(nanopore) labuser@JCSMR-049555LD:~/lib/xpore/demo/data/HEK293T-WT-rep1$ xpore-dataprep --eventalign nanopolish/eventalign.txt --summary nanopolish/summary.txt --out_dir dataprep --genome
Process Consumer-1:
Traceback (most recent call last):
  File "/home/labuser/anaconda3/envs/nanopore/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/labuser/anaconda3/envs/nanopore/lib/python3.7/site-packages/xpore-0.5.2-py3.7.egg/xpore/scripts/helper.py", line 77, in run
    result = self.task_function(*next_task_args,self.locks)
  File "/home/labuser/anaconda3/envs/nanopore/lib/python3.7/site-packages/xpore-0.5.2-py3.7.egg/xpore/scripts/dataprep.py", line 78, in combine
    df2write = df_events_per_read.loc[[tx_id,read_id],:].reset_index()
  File "/home/labuser/anaconda3/envs/nanopore/lib/python3.7/site-packages/pandas/core/indexing.py", line 873, in __getitem__
    return self._getitem_tuple(key)
  File "/home/labuser/anaconda3/envs/nanopore/lib/python3.7/site-packages/pandas/core/indexing.py", line 1044, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "/home/labuser/anaconda3/envs/nanopore/lib/python3.7/site-packages/pandas/core/indexing.py", line 766, in _getitem_lowerdim
    return self._getitem_nested_tuple(tup)
  File "/home/labuser/anaconda3/envs/nanopore/lib/python3.7/site-packages/pandas/core/indexing.py", line 847, in _getitem_nested_tuple
    obj = getattr(obj, self.name)._getitem_axis(key, axis=axis)
  File "/home/labuser/anaconda3/envs/nanopore/lib/python3.7/site-packages/pandas/core/indexing.py", line 1099, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
  File "/home/labuser/anaconda3/envs/nanopore/lib/python3.7/site-packages/pandas/core/indexing.py", line 1037, in _getitem_iterable
    keyarr, indexer = self._get_listlike_indexer(key, axis, raise_missing=False)
  File "/home/labuser/anaconda3/envs/nanopore/lib/python3.7/site-packages/pandas/core/indexing.py", line 1240, in _get_listlike_indexer
    indexer, keyarr = ax._convert_listlike_indexer(key)
  File "/home/labuser/anaconda3/envs/nanopore/lib/python3.7/site-packages/pandas/core/indexes/multi.py", line 2397, in _convert_listlike_indexer
    raise KeyError(f"{keyarr[mask]} not in index")
KeyError: "['decfc830-9eb6-4a10-97fb-d117db06178d'] not in index"
```
Thanks

**Comment by ploy-np** [comment]
Hi @pabloacera, @madnessfish,

Because from v0.5.1 to v0.5.2, I changed the data structure in eventalign.hdf5, one of the outputs from xpore-dataprep. Can you check if you removed this file before you run xpore-dataprep? If you still have the error, please let me know.

**Comment by pabloacera** [comment]
Hi, 
Thanks for the answer. I currently have no eventalign.hdf5, this is my file structure:

`drwxr-xr-x 6 labuser labuser  4096 Aug 11 14:30 ./
drwxr-xr-x 4 labuser labuser  4096 May 26 20:56 ../
drwxr-xr-x 2 labuser labuser  4096 May  5 16:02 bamtx/
drwxr-xr-x 2 labuser labuser 61440 May 25 16:55 fast5/
drwxr-xr-x 2 labuser labuser  4096 May 25 16:54 fastq/
drwxr-xr-x 2 labuser labuser  4096 May  5 15:42 nanopolish/
(nanopore) labuser@JCSMR-049555LD:~/lib/xpore/demo/data/HEK293T-METTL3-KO-rep1$`

this is my command. 
```

(nanopore) labuser@JCSMR-049555LD:~/lib/xpore/demo/data/HEK293T-METTL3-KO-rep1$ xpore-dataprep --eventalign nanopolish/eventalign.txt --summary nanopolish/summary.txt --out_dir dataprep --genome
Process Consumer-1:
Traceback (most recent call last):
  File "/home/labuser/anaconda3/envs/nanopore/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/labuser/anaconda3/envs/nanopore/lib/python3.7/site-packages/xpore-0.5.2-py3.7.egg/xpore/scripts/helper.py", line 77, in run
    result = self.task_function(*next_task_args,self.locks)
  File "/home/labuser/anaconda3/envs/nanopore/lib/python3.7/site-packages/xpore-0.5.2-py3.7.egg/xpore/scripts/dataprep.py", line 78, in combine
    df2write = df_events_per_read.loc[[tx_id,read_id],:].reset_index()
  File "/home/labuser/anaconda3/envs/nanopore/lib/python3.7/site-packages/pandas/core/indexing.py", line 873, in __getitem__
    return self._getitem_tuple(key)
  File "/home/labuser/anaconda3/envs/nanopore/lib/python3.7/site-packages/pandas/core/indexing.py", line 1044, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "/home/labuser/anaconda3/envs/nanopore/lib/python3.7/site-packages/pandas/core/indexing.py", line 766, in _getitem_lowerdim
    return self._getitem_nested_tuple(tup)
  File "/home/labuser/anaconda3/envs/nanopore/lib/python3.7/site-packages/pandas/core/indexing.py", line 847, in _getitem_nested_tuple
    obj = getattr(obj, self.name)._getitem_axis(key, axis=axis)
  File "/home/labuser/anaconda3/envs/nanopore/lib/python3.7/site-packages/pandas/core/indexing.py", line 1099, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
  File "/home/labuser/anaconda3/envs/nanopore/lib/python3.7/site-packages/pandas/core/indexing.py", line 1037, in _getitem_iterable
    keyarr, indexer = self._get_listlike_indexer(key, axis, raise_missing=False)
  File "/home/labuser/anaconda3/envs/nanopore/lib/python3.7/site-packages/pandas/core/indexing.py", line 1240, in _get_listlike_indexer
    indexer, keyarr = ax._convert_listlike_indexer(key)
  File "/home/labuser/anaconda3/envs/nanopore/lib/python3.7/site-packages/pandas/core/indexes/multi.py", line 2397, in _convert_listlike_indexer
    raise KeyError(f"{keyarr[mask]} not in index")
KeyError: "['e2e8889a-e12c-4bb9-b5c6-142b1246d31f'] not in index"

```
thanks!

**Comment by ploy-np** [comment]
Hi @pabloacera, @madnessfish,

I found a mistake! xpore v0.5.2 is not the latest update relative to my github branch yet. That's why I didn't have the error in my local machine. 

Now, I published a latest version (xpore v0.5.3). Could you please update and try again?

Apologies for this!

**Comment by pabloacera** [comment]
That's completely fine! thanks a lot for taking the time! =)

**Comment by pabloacera** [comment]
Hi, 
Somehow it was still failing for me. I made a simple change in the script xpore-dataprep, adding parenthesis to line 79.
`df2write = df_events_per_read.loc[[(tx_id,read_id)],:].reset_index()
`
 I have already made a pull request just in case, probably you fixed it in another version. 
Thanks again and sorry for the inconveniences

**Comment by ploy-np** [comment]
Hi @pabloacera,
Thank you so much! I will test and merge your comment in the future version.
So, after you added the parenthesis, everything works fine?

**Comment by pabloacera** [comment]
exactly! for me after that, xpore-dataprep worked fine and then xpore-diffmod --config Hek293T_config.yml also worked!
Cheers!

**Comment by ploy-np** [comment]
Thanks a lot @pabloacera

**Comment by ploy-np** [comment]
This was fixed in the release v0.5.4 already. May I close this comment. Thank you very much @pabloacera @madnessfish.
